CREATE TABLE EMPLOYEE(
EMPNAME VARCHAR(20),
EMPDEG VARCHAR(20),
EMPSALARY INT
);
ALTER TABLE EMPLOYEE ADD BRANCH VARCHAR(255);
INSERT INTO EMPLOYEE VALUES('RAM','MANAGER',500000,'CHENNAI');
INSERT INTO EMPLOYEE VALUES('HARI','ASSISTANT',300000,'TRICHY');
SELECT * FROM EMPLOYEE