CREATE TABLE EMPLOYEE(
EMPID INT,
EMPNAME VARCHAR(20),
EMPSALARY INT);
INSERT INTO EMPLOYEE VALUES(10,'HARI',30000);
INSERT INTO EMPLOYEE VALUES(110,'HARISH',40000);
Delete from Employee WHERE EMPID=110;
SELECT * FROM EMPLOYEE