-- create a table
CREATE TABLE ACTORS(
ID INT(10),
NAME varchar(100),
AGE INT(10)
);
-- insert some values
INSERT INTO ACTORS VALUES (1,'SANDEEP',19);
INSERT INTO ACTORS VALUES (2,'SANDY',20);
INSERT INTO ACTORS VALUES (3,'SAI',22);
INSERT INTO ACTORS VALUES (4,'SANTHU',21);
SELECT NAME,AGE FROM ACTORS WHERE ID IS 2 GROUP by NAME;
