-- create a table
CREATE TABLE EMPLOYEE (
    EMPID INT,
    EMPNAME VARCHAR(20),
    EMPSALARY INT(10)
);
-- insert some values
INSERT INTO EMPLOYEE VALUES(1,'HARI',30000);
INSERT INTO EMPLOYEE VALUES(2,'SAI',40000);
INSERT INTO EMPLOYEE VALUES(3,'GIRI',50000);
INSERT INTO EMPLOYEE VALUES(4,'HARISH',60000);
SELECT * FROM EMPLOYEE
WHERE EMPNAME IN ('HARI','SANDEEP','GIRI')